/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tragamonedas;

import javax.swing.JOptionPane;

/**
 *
 * @author Edward
 */
public class Juego extends javax.swing.JFrame {

    int monedas = 20;

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb5 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        lb7 = new javax.swing.JLabel();
        lb8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbMonedas = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        play = new javax.swing.JButton();
        lb9 = new javax.swing.JLabel();
        lb10 = new javax.swing.JLabel();
        lb11 = new javax.swing.JLabel();
        lb12 = new javax.swing.JLabel();
        lb19 = new javax.swing.JLabel();
        lb21 = new javax.swing.JLabel();
        lb22 = new javax.swing.JLabel();
        lb23 = new javax.swing.JLabel();
        lb24 = new javax.swing.JLabel();
        lb25 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb26 = new javax.swing.JLabel();
        lb27 = new javax.swing.JLabel();

        lb5.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lb5.setText("9");

        lb6.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lb6.setText("9");

        lb7.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lb7.setText("9");

        lb8.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lb8.setText("9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MAQUINA TRAGA MONEDAS");

        lbMonedas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbMonedas.setText("MONEDAS 20");

        lb1.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reloj.png"))); // NOI18N
        lb1.setText("9");

        lb2.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numero7detragamonedas.png"))); // NOI18N

        lb3.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lb3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casa.png"))); // NOI18N

        play.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        play.setText("PLAY");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        lb9.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lb9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uva.png"))); // NOI18N

        lb10.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lb10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robot.png"))); // NOI18N

        lb11.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lb11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Moto 5.png"))); // NOI18N

        lb12.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lb12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carro 4.jpg"))); // NOI18N

        lb19.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lb19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anillo.png"))); // NOI18N

        lb21.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lb21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anillo.png"))); // NOI18N

        lb22.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lb22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uva.png"))); // NOI18N

        lb23.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lb23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robot.png"))); // NOI18N

        lb24.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lb24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Moto 5.png"))); // NOI18N

        lb25.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lb25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carro 4.jpg"))); // NOI18N

        lb4.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lb4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reloj.png"))); // NOI18N
        lb4.setText("9");

        lb26.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lb26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numero7detragamonedas.png"))); // NOI18N

        lb27.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lb27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casa.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb24, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb22)
                        .addGap(35, 35, 35)
                        .addComponent(play))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(lbMonedas)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMonedas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb2)
                    .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb3)
                    .addComponent(lb19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb9)
                    .addComponent(lb12)
                    .addComponent(lb11)
                    .addComponent(lb10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb26)
                    .addComponent(lb4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb27)
                    .addComponent(lb21))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb22)
                            .addComponent(lb25)
                            .addComponent(lb24)
                            .addComponent(lb23))
                        .addGap(243, 243, 243))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(play)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        // TODO add your handling code here:
        monedas -= 1;
        int slot1 = (int) (Math.random() * 9 + 1);
        int slot2 = (int) (Math.random() * 9 + 1);
        int slot3 = (int) (Math.random() * 9 + 1);
        int slot4 = (int) (Math.random() * 9 + 1);
        lb1.setText(String.valueOf(slot1));
        lb2.setText(String.valueOf(slot2));
        lb3.setText(String.valueOf(slot3));
        lb4.setText(String.valueOf(slot4));
        if (slot1 == slot2 && slot2 == slot3 && slot3 == slot4) {
            switch (slot1) {
                case 7:
                    monedas += 90 + 1;
                    JOptionPane.showMessageDialog(this, "GANASTE 90 monedas");
                    break;
                case 9:
                    monedas += 50 + 1;
                    JOptionPane.showMessageDialog(this, "GANASTE 50 monedas");
                    break;
                case 3:
                    monedas += 20 + 1;
                    JOptionPane.showMessageDialog(this, "GANASTE 20 monedas");
                    break;
                case 1:
                    monedas += 10 + 1;
                    JOptionPane.showMessageDialog(this, "GANASTE 10 monedas");
                    break;
                default:
                    monedas += slot1 + 1;
                    JOptionPane.showMessageDialog(this, "GANASTE" + slot1+ "monedas");
                     break;
            }
        }
        lbMonedas.setText("Monedas " + String.valueOf(monedas));
        if (monedas == 0) {
            int numero = JOptionPane.showConfirmDialog(this, "Juegas de NUEVO?", "Maquina Traga Monedas", JOptionPane.YES_NO_OPTION);
            if (numero == 0) {
                monedas = 20;
                lbMonedas.setText("Monedas " + String.valueOf(monedas));
            } else {
               System.exit(0);
            }
        }
    }//GEN-LAST:event_playActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb10;
    private javax.swing.JLabel lb11;
    private javax.swing.JLabel lb12;
    private javax.swing.JLabel lb19;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb21;
    private javax.swing.JLabel lb22;
    private javax.swing.JLabel lb23;
    private javax.swing.JLabel lb24;
    private javax.swing.JLabel lb25;
    private javax.swing.JLabel lb26;
    private javax.swing.JLabel lb27;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel lb8;
    private javax.swing.JLabel lb9;
    private javax.swing.JLabel lbMonedas;
    private javax.swing.JButton play;
    // End of variables declaration//GEN-END:variables
}
